branches:
  - name: "main"
  - name: "release"
  - name: "prerelease"
    prerelease: "snapshot"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", {changelogFile: "CHANGELOG.md"}]
  - "gradle-semantic-release-plugin"
  - [
    "@semantic-release/git",
    {
      assets: [
        "CHANGELOG.md",
        "gradle.properties"
      ],
      message: "chore(release): cut wallet sdk version ${nextRelease.version}

        ${nextRelease.notes}",
    },
  ]
  - [
    "semantic-release-slack-bot",
    {
      notifyOnSuccess: true,
      notifyOnFail: true,
      markdownReleaseNotes: true,
      onSuccessTemplate:
        {text: "A new version of `$package_name` successfully released!\n
            Version: `v$npm_package_version`\n
            Tag: $repo_url/releases/tag/v$npm_package_version \n
            \n
            Release notes:\n
            $release_notes"},
    },
  ]
