---
name: 'Feature Request'
description: Suggest a new feature for Atala PRISM DIDComm

body:
  - type: textarea
    id: proposed-feature
    attributes:
      label: Proposed feature
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature description
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?
