---
# kics-scan ignore
name: "Linter"

defaults:
  run:
    shell: bash

on:
  pull_request:

jobs:
  lint:
    name: Lint changes
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ATALA_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Mega-Linter
        id: ml
        uses: oxsecurity/megalinter@v7.4.0

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Mega-Linter reports
          path: |
            megalinter-reports
            mega-linter.log
